modeladorsemantiko_light/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
# Uncomment the next two lines to enable the admin:

from django.views import generic
import autocomplete_light
from efectorescas.views import efectoresVistaImagenes, search
from modeladorFarmacos.forms import bioeqForm


autocomplete_light.autodiscover()

from django.contrib import admin
admin.autodiscover()

from modeloNanda.api import EntryResource, UserResource
from tastypie.api import Api

from modeladorFarmacos.views import *
import modeladorFarmacos.views

from repodocumentos.views import ArchivoDetalleVista,ArchivosSubidosView,ArchivoIndiceVista
from repocasos.views import ListCaseView,CreateCaseView, UpdateCaseView,DeleteCaseView,CaseView

from repocasos.forms import CasoForm

v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(EntryResource())

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'modeladorsemantiko_light.views.home', name='home'),
    # url(r'^modeladorsemantiko_light/', include('modeladorsemantiko_light.foo.urls')),
    url(r'^modelador_light/autocomplete/', include('autocomplete_light.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^modelador_light/admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^modelador_light/login/$', 'django.contrib.auth.views.login'),
    url(r'^modelador_light/logout/$', 'django.contrib.auth.views.logout'),

    # Uncomment the next line to enable the admin:
    url(r'^modelador_light/admin/', include(admin.site.urls)),

    (r'^modelador_light/api/', include(v1_api.urls)),
    (r'^modelador_light/favicon.ico', generic.RedirectView.as_view(url='http://mozilla.org/favicon.ico')),

    (r'^modelador_light/$', generic.TemplateView.as_view(template_name='index.html')),

    (r'^modelador_light/my_admin/jsi18n', 'django.views.i18n.javascript_catalog'),

    url(r'^modelador_light/xt_pcce/lista_usuarios/$', modeladorFarmacos.views.VistaListaPCCECreadores.as_view(),
        name='creadores_lista',),

    url(r'^modelador_light/xt_pcce/lista_usuarios/(\w+)/$', modeladorFarmacos.views.VistaUsuarioCreadorPCCE.as_view()),

    url(r'^modelador_light/xt_pc/lista_usuarios/$', modeladorFarmacos.views.VistaListaPCCreadores.as_view(),
        name='creadores_lista',),

    url(r'^modelador_light/xt_pc/lista_usuarios/(\w+)/$', modeladorFarmacos.views.VistaUsuarioCreadorPC.as_view()),


    url(r'^modelador_light/xt_pc/lista_pendientes/$', modeladorFarmacos.views.VistaPorRevisarPC.as_view(),
        name='lista_pendientes',),


    url(r'^modelador_light/xt_pcce/lista_pendientes/$', modeladorFarmacos.views.VistaPorRevisarPCCE.as_view(),
        name='lista_pendientes',),


##Vistas Para Creacion de Nuevos Bioequivalentes
    url(r'^modelador_light/bioeq/$', modeladorFarmacos.views.VistaBioequivalente.as_view(),
        name='bioeq-lista',),

    url(r'^modelador_light/admin/modeladorFarmacos/xt_bioequivalente/add/$', generic.CreateView.as_view(model=xt_bioequivalente, form_class=bioeqForm, template_name='modeladorFarmacos/crea_bioequivalente.html'),
        name='bioeq-nuevo',),

    url(r'^modelador_light/admin/modeladorFarmacos/xt_bioequivalente/(?P<pk>\d+)/$', modeladorFarmacos.views.EditaBioequivalente.as_view(),
        name='bioeq-editar',),


##Creacion de productos Segun Kairos
    #    (r'^modelador/catalogo/$', lista_mc),
    (r'^modelador_light/pendientes/$', pendientes),


    (r'^modelador_light/kairos_capsulas/$', kairos2),

    (r'^modelador_light/kairos/$', kairos_global),
    (r'^modelador_light/kairos_tabletas/$', kairos_tabletas),
    (r'^modelador_light/kairos_gotas/$', kairos_gotas),
    (r'^modelador_light/kairos_jarabes/$', kairos_jarabes),
    (r'^modelador_light/kairos_ampollas/$', kairos_ampollas),
    (r'^modelador_light/kairos_colirios/$', kairos_colirios),
    (r'^modelador_light/kairos_cremas/$', kairos_cremas),
    (r'^modelador_light/kairos_parches/$', kairos_parches),
    (r'^modelador_light/kairos_shampoo/$', kairos_shampoo),
    (r'^modelador_light/kairos_supositorios/$', kairos_supositorios),

    ###Efectores CAS
    (r'modelador_light/efectores/imagenes/$', efectoresVistaImagenes),


    (r'^modelador_light/search-form/$', search),

##Repositorio de Documentos
    url(r'^modelador_light/subir/', ArchivosSubidosView.as_view(), name='archivo_upload'),
    url(r'^modelador_light/lista_subidos/(?P<pk>\d+)/$', ArchivoDetalleVista.as_view (),
        name='archivo_subido'),
    url(r'^modelador_light/lista_subidos/', ArchivoIndiceVista.as_view (),
        name='archivo_lista'),
    url(r'^modelador_light/media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'media'}),

##Repositorio de Casos
    url(r'^modelador_light/casos/$', ListCaseView.as_view(),
        name='case-list',),
    url(r'^modelador_light/casos/nuevo', CreateCaseView.as_view(form_class=CasoForm),
        name='case-new',),
    url(r'^modelador_light/casos/editar/(?P<pk>\d+)/$', UpdateCaseView.as_view(),
        name='case-edit',),
    url(r'^modelador_light/casos/borrar/(?P<pk>\d+)/$', DeleteCaseView.as_view(),
        name='case-delete',),
    url(r'^modelador_light/casos/(?P<pk>\d+)/$', CaseView.as_view(),
        name='case-view',),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

efectorescas/models.py
from django.contrib.auth.models import User
from django.db import models
from mptt.models import MPTTModel, TreeForeignKey





class BaseModel(models.Model):
    fecha_creacion = models.DateTimeField(null=False, auto_now_add=True)
    usuario_creador = models.ForeignKey(User, null=False, blank=False, editable=False, related_name='%(app_label)s_%(class)s_related_crea', default=1)
    fecha_ult_mod = models.DateTimeField(null=True, auto_now=True)
    usuario_ult_mod = models.ForeignKey(User, null=True, blank=False, editable=False, related_name='%(app_label)s_%(class)s_related_modif', default=1)

    class Meta:
        abstract = True


class concepto(BaseModel):
    OPCIONES_DOMINIO = ((1, 'Imagenes'),(2, 'Procedimientos'),(3,'Laboratorio'),(4,'Takion'))
    fsn = models.CharField('Fully Specified Name',max_length=255, )
    revisado = models.BooleanField(default=1)
    dominio = models.IntegerField(choices=OPCIONES_DOMINIO, default=1)
    pedible = models.BooleanField(default=1)
    dominio_nucleo = models.IntegerField(choices=OPCIONES_DOMINIO, default=1)

    def descripciones(objeto):
        return '<br/>'.join(c.termino for c in objeto.descripcion_set.order_by('id')[:4])

    descripciones.allow_tags = True
    descripciones.short_description = 'Descripcion'

    def get_areas(self):
        return '<br/>'.join(c.descripcion for c in self.cas_area_set.order_by('id')[:4])
    get_areas.allow_tags = True
    get_areas.short_description = 'Areas'

    def __unicode__(self):
        return self.fsn
    class Meta:
        ordering=['id']
        verbose_name_plural = "conceptos"

class cas_area(BaseModel):
    descripcion = models.CharField(max_length=255)
    conceptosporarea = models.ManyToManyField(concepto, through='conceptosCASporarea')

    def conceptos (objeto):
        return '<br/>'.join(c.fsn for c in objeto.conceptosporarea.order_by('id')[:4])
    conceptos.allow_tags = True
    conceptos.short_description = 'Conceptos'


    def __unicode__(self):
        return self.descripcion
    class Meta:
        ordering=['id']
        verbose_name_plural = "Areas CAS"

class cas_lugar(models.Model):
    descripcion = models.CharField(max_length=255)
    areas = models.ForeignKey(cas_area)

    def __unicode__(self):
        return self.descripcion
    class Meta:
        ordering=['id']
        verbose_name_plural = "Lugares CAS"


class descripcion(BaseModel):
    OPCIONES_TIPO = (
        (1,'Preferido'),
        (2,'Sinonimo Visible'),
        #        (3,'Descripcion Completa'),
        #        (4,'Error tipografico'),
        )
    termino = models.CharField(max_length=255)
    id_concepto = models.ForeignKey(concepto, null=True, blank=True)
    tipodescripcion = models.IntegerField(choices=OPCIONES_TIPO)

    def __unicode__(self):
        return self.termino
    class Meta:
        ordering=['id']
        verbose_name_plural = "descripciones"


class conceptosCASporarea(BaseModel):
    concepto = models.ForeignKey(concepto)
    area = models.ForeignKey(cas_area)

    def get_efectorxarea(objeto):
        return '<br/>'.join("[%s] %s" % (c.efector.ExamCode, c.efector.ExamName) for c in objeto.efector_codigoporarea_set.order_by('id')[:4])
    get_efectorxarea.allow_tags = True
    get_efectorxarea.short_description = 'Efectores'

    def __unicode__(self):
        return "%s | %s" % (self.concepto.fsn, self.area.descripcion)
    class Meta:
        ordering=['id']
        verbose_name_plural = "Conceptos CAS por Area"


class efector(MPTTModel):
    OPCIONES_DOMINIO = ((1, 'Imagenes'),(2, 'Procedimientos'),(3,'Laboratorio'))
    ExamCode = models.CharField(max_length=255, primary_key=True)
    ExamName = models.CharField(max_length=255)
    dominio = models.IntegerField(choices=OPCIONES_DOMINIO)
    codigoporarea = models.ManyToManyField(conceptosCASporarea, through='efector_codigoporarea')


    fecha_creacion = models.DateTimeField(null=False, auto_now_add=True)
    usuario_creador = models.ForeignKey(User, null=False, blank=False, editable=False, related_name='%(app_label)s_%(class)s_related_crea', default=1)
    fecha_ult_mod = models.DateTimeField(null=True, auto_now=True)
    usuario_ult_mod = models.ForeignKey(User, null=True, blank=False, editable=False, related_name='%(app_label)s_%(class)s_related_modif', default=1)

    parent = TreeForeignKey('self', null=True, blank=True, related_name='hijos')

    class MPTTMeta:
        order_insertion_by = ['ExamName']


    def get_conceptosporarea(objeto):
        return '<br/>'.join(c.concepto.fsn for c in objeto.codigoporarea.order_by('id')[:4])
    get_conceptosporarea.allow_tags = True
    get_conceptosporarea.short_description = 'Conceptos'

    def get_areas(objeto):
        return '<br/>'.join(c.area.descripcion for c in objeto.codigoporarea.order_by('id')[:4])
    get_areas.allow_tags = True
    get_areas.short_description = 'Areas'

    def __unicode__(self):
        return '%s | %s' % (self.ExamCode,self.ExamName)
    class Meta:
        ordering=['ExamName']
        verbose_name_plural = "efectores"


class efector_codigoporarea(BaseModel):
    efector = models.ForeignKey(efector)
    conceptoscasporarea = models.ForeignKey(conceptosCASporarea, verbose_name='Concepto x Area')


    def __unicode__(self):
        return u'%s' % self.efector

efectorescas/forms.py
from django import forms

class SearchForm(forms.Form):
    query = forms.CharField(
        label='',
        widget=forms.TextInput(attrs={'size':60})
    )

__author__ = 'ehebel'

efectorescas/views.py
from django.core.paginator import EmptyPage, Paginator, InvalidPage
from django.shortcuts import render_to_response, render
from django.template import RequestContext
from efectorescas.forms import SearchForm
from efectorescas.models import concepto

import re

from django.db.models import Q

def normalize_query(query_string,
                    findterms=re.compile(r'"([^"]+)"|(\S+)').findall,
                    normspace=re.compile(r'\s{2,}').sub):
    ''' Splits the query string in invidual keywords, getting rid of unecessary spaces
        and grouping quoted words together.
        Example:

        >>> normalize_query('  some random  words "with   quotes  " and   spaces')
        ['some', 'random', 'words', 'with quotes', 'and', 'spaces']

    '''
    return [normspace(' ', (t[0] or t[1]).strip()) for t in findterms(query_string)]

def get_query(query_string, search_fields):
    ''' Returns a query, that is a combination of Q objects. That combination
        aims to search keywords within a model by testing the given search fields.

    '''
    query = None # Query to search for every search term
    terms = normalize_query(query_string)
    for term in terms:
        or_query = None # Query to search for a given term in each field
        for field_name in search_fields:
            q = Q(**{"%s__icontains" % field_name: term})
            if or_query is None:
                or_query = q
            else:
                or_query = or_query | q
        if query is None:
            query = or_query
        else:
            query = query & or_query
    return query


def efectoresVistaImagenes(request):
    img_list = concepto.objects.filter(dominio__exact=1).order_by('fsn').all()

    paginator = Paginator(img_list, 200)

    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1

    try:
        imagenes = paginator.page(page)
    except(EmptyPage, InvalidPage):
        imagenes = paginator.page(paginator.num_pages)


    return render_to_response('efectoresCAS/vista_imagenes.html'
        ,{'modelados_imagenes':imagenes},
        context_instance=RequestContext(request))



def search(request):
    form = SearchForm()
    examenes = []

    img_list = concepto.objects.filter(dominio__exact=1).order_by('fsn').all()
    paginator = Paginator(img_list, 200)
    try:
        page = int(request.GET.get('page','1'))
    except:
        page = 1
    try:
        imagenes = paginator.page(page)
    except(EmptyPage, InvalidPage):
        imagenes = paginator.page(paginator.num_pages)

    show_results = False
    if 'query' in request.GET and request.GET['query']:
        show_results = True
        query = request.GET['query'].strip()
        entry_query = get_query(query,['fsn',])
        if entry_query:
            form = SearchForm({'query': query})
            examenes = concepto.objects.filter(entry_query, dominio=1).order_by('fsn')

    variables = RequestContext(request, {   'form': form,
                                            'modelados_imagenes': examenes,
                                            'show_results': show_results,
                                            'todos': imagenes,
                                            })
    if 'ajax' in request.GET:
        return render_to_response('efectoresCAS/search_results.html', variables)
    else:
        return  render_to_response('efectoresCAS/search_form.html', variables)

templates/efectoresCAS/search.html
<br>
{% block content %}
<table border=3 cellpadding=3 width=100%>
    <tr>
        <th>Conceptos</th>
        <th>Descripciones</th>
        <th>Areas</th>
        <th>Efectores</th>
    </tr>{% for item in todos %}
    <tr>
        <td rowspan={% if item.cas_area_set.all|length == 0 %}1{% else %}{{ item.cas_area_set.all|length }}{% endif %}>

            <a href="/modelador_light/admin/efectorescas/concepto/{{ item.id }}">{{ item.fsn }}</a>
        </td>

        <td rowspan={% if item.cas_area_set.all|length == 0 %}1{% else %}{{ item.cas_area_set.all|length }}{% endif %}>

            {% for desc in item.descripcion_set.all %} <li>{{ desc.termino }} </li>{% endfor %}
        </td>
        {% for area in item.conceptoscasporarea_set.all %}

            <td>
                {{ area.area }}
            </td>


            <td>


                {% for codarea in area.efector_codigoporarea_set.all %}
                    <li>[{{ codarea.efector.ExamCode }}] <a href="/modelador_light/admin/efectorescas/efector_codigoporarea/{{ codarea.id }}">{{ codarea.efector.ExamName }}</li></a>


                {% endfor %}
            </td>

            </tr>
        {% endfor %}
{% endfor %}

</table>



    <div class="pagination">
        {% if todos.has_previous %}
            <a href="?page={{ todos.previous_page_number }}">&#171 Anterior</a>
        {% endif %}
        {% for pg in todos.paginator.page_range %}
            {% if todos.number == pg %}
                <span class="active"><a href="?page={{ pg }}">{{ pg }}</a>|</span>
            {% else %}
                <span><a href="?page={{ pg }}">{{ pg }}</a> |</span>
            {% endif %}
        {% endfor %}
        {% if todos.has_next %}
            <span><a href="?page={{ todos.next_page_number }}">Siguiente &#187;</a></span>
        {% endif %}
    </div>
{% endblock %}

templates/efectoresCAS/search_form.html
{% extends 'base.html' %}
{% block external %}
    <script type="text/javascript" src="/modelador_light/static/search.js"></script>
{% endblock %}
{% block title %}Buscar Examenes{% endblock %}
{% block head %}Buscar Examenes{% endblock %}

{% block branding %}
    <h1>Efectores Imágenes</h1>
{% endblock %}

{% block content %}


    <form id="search-form" method="get" action=".">
        {{ form }}
        <input type="submit" value="Buscar" />
    </form>

    <div id="search-results">
        {%  if show_results %}

            {% include 'efectoresCAS/search_results.html' %}

        {% else %}

            {% include 'efectoresCAS/search.html' %}

        {% endif %}
    </div>

{% endblock %}

templates/efectoresCAS/search_results.html
<br>
{% block content %}
    {% if modelados_imagenes %}
        <p>Encontramos {{ modelados_imagenes|length }} exámenes.</p>

        <table border=3 cellpadding=3 width=100%>
            <tr>
                <th>Conceptos</th>
                <th>Descripciones</th>
                <th>Areas</th>
                <th>Efectores</th>
            </tr>{% for item in modelados_imagenes %}
            <tr>
                <td rowspan={% if item.cas_area_set.all|length == 0 %}1{% else %}{{ item.cas_area_set.all|length }}{% endif %}>

                    <a href="/modelador_light/admin/efectorescas/concepto/{{ item.id }}">{{ item.fsn }}</a>
                </td>

                <td rowspan={% if item.cas_area_set.all|length == 0 %}1{% else %}{{ item.cas_area_set.all|length }}{% endif %}>

                    {% for desc in item.descripcion_set.all %} <li>{{ desc.termino }} </li>{% endfor %}
                </td>
                {% for area in item.conceptoscasporarea_set.all %}

                    <td>
                        {{ area.area }}
                    </td>


                    <td>


                        {% for codarea in area.efector_codigoporarea_set.all %}
                            <li>[{{ codarea.efector.ExamCode }}] <a href="/modelador_light/admin/efectorescas/efector_codigoporarea/{{ codarea.id }}"> {{ codarea.efector.ExamName }} </li></a>


                        {% endfor %}
                    </td>

                    </tr>
                {% endfor %}
        {% endfor %}

        </table>


    {% else %}
        No hubo coincidencias!
    {% endif %}
{% endblock %}

templates/efectoresCAS/vista_imagenes.html
{% extends 'base.html' %}
{% block title %}Efectores Examenes{% endblock %}
{% block head %}Efectores Examenes{% endblock %}

{% block branding %}
    <h1>Efectores Imágenes</h1>
{% endblock %}
<br>
{% block content %}

    {% if modelados_imagenes %}


    <table border=3 cellpadding=3 width=100%>
        <tr>
            <th>Conceptos</th>
            <th>Descripciones</th>
            <th nowrap="nowrap">Areas</th>
            <th>Efectores</th>
        </tr>{% for item in modelados_imagenes %}
        <tr>
            <td rowspan={% if item.cas_area_set.all|length == 0 %}1{% else %}{{ item.cas_area_set.all|length }}{% endif %}>

                <a href="/modelador_light/admin/efectorescas/concepto/{{ item.id }}">{{ item.fsn }}</a>
            </td>

            <td rowspan={% if item.cas_area_set.all|length == 0 %}1{% else %}{{ item.cas_area_set.all|length }}{% endif %}>

            {% for desc in item.descripcion_set.all %} <li>{{ desc.termino }} </li>{% endfor %}
            </td>
            {% for area in item.conceptoscasporarea_set.all %}

                    <td>
                        {{ area.area }}
                    </td>


            <td>


                    {% for codarea in area.efector_codigoporarea_set.all %}
                        <li>[{{ codarea.efector.ExamCode }}] <a href="/modelador_light/admin/efectorescas/efector_codigoporarea/{{ codarea.id }}">{{ codarea.efector.ExamName }}</li></a>


            {% endfor %}
            </td>

        </tr>
        {% endfor %}
    {% endfor %}

    </table>




    <div class="pagination">
        {% if modelados_imagenes.has_previous %}
            <a href="?page={{ modelados_imagenes.previous_page_number }}">&#171 Anterior</a>
        {% endif %}
        {% for pg in modelados_imagenes.paginator.page_range %}
            {% if modelados_imagenes.number == pg %}
                <span class="active"><a href="?page={{ pg }}">{{ pg }}</a>|</span>
            {% else %}
                <span><a href="?page={{ pg }}">{{ pg }}</a> |</span>
            {% endif %}
        {% endfor %}
        {% if modelados_imagenes.has_next %}
            <span><a href="?page={{ modelados_imagenes.next_page_number }}">Siguiente &#187;</a></span>
        {% endif %}
    </div>

    {% else %}
        No hubo coincidencias!
    {% endif %}
{% endblock %}