modeladorsemantiko_light/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
# Uncomment the next two lines to enable the admin:

from django.views import generic
import autocomplete_light
from efectorescas.views import efectoresVistaImagenes, search
from modeladorFarmacos.forms import bioeqForm


autocomplete_light.autodiscover()

from django.contrib import admin
admin.autodiscover()

from modeloNanda.api import EntryResource, UserResource
from tastypie.api import Api

from modeladorFarmacos.views import *
import modeladorFarmacos.views

from repodocumentos.views import ArchivoDetalleVista,ArchivosSubidosView,ArchivoIndiceVista
from repocasos.views import ListCaseView,CreateCaseView, UpdateCaseView,DeleteCaseView,CaseView

from repocasos.forms import CasoForm

v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(EntryResource())

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'modeladorsemantiko_light.views.home', name='home'),
    # url(r'^modeladorsemantiko_light/', include('modeladorsemantiko_light.foo.urls')),
    url(r'^modelador_light/autocomplete/', include('autocomplete_light.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^modelador_light/admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^modelador_light/login/$', 'django.contrib.auth.views.login'),
    url(r'^modelador_light/logout/$', 'django.contrib.auth.views.logout'),

    # Uncomment the next line to enable the admin:
    url(r'^modelador_light/admin/', include(admin.site.urls)),

    (r'^modelador_light/api/', include(v1_api.urls)),
    (r'^modelador_light/favicon.ico', generic.RedirectView.as_view(url='http://mozilla.org/favicon.ico')),

    (r'^modelador_light/$', generic.TemplateView.as_view(template_name='index.html')),

    (r'^modelador_light/my_admin/jsi18n', 'django.views.i18n.javascript_catalog'),

    url(r'^modelador_light/xt_pcce/lista_usuarios/$', modeladorFarmacos.views.VistaListaPCCECreadores.as_view(),
        name='creadores_lista',),

    url(r'^modelador_light/xt_pcce/lista_usuarios/(\w+)/$', modeladorFarmacos.views.VistaUsuarioCreadorPCCE.as_view()),

    url(r'^modelador_light/xt_pc/lista_usuarios/$', modeladorFarmacos.views.VistaListaPCCreadores.as_view(),
        name='creadores_lista',),

    url(r'^modelador_light/xt_pc/lista_usuarios/(\w+)/$', modeladorFarmacos.views.VistaUsuarioCreadorPC.as_view()),


    url(r'^modelador_light/xt_pc/lista_pendientes/$', modeladorFarmacos.views.VistaPorRevisarPC.as_view(),
        name='lista_pendientes',),


    url(r'^modelador_light/xt_pcce/lista_pendientes/$', modeladorFarmacos.views.VistaPorRevisarPCCE.as_view(),
        name='lista_pendientes',),


##Vistas Para Creacion de Nuevos Bioequivalentes
    url(r'^modelador_light/bioeq/$', modeladorFarmacos.views.VistaBioequivalente.as_view(),
        name='bioeq-lista',),

    url(r'^modelador_light/admin/modeladorFarmacos/xt_bioequivalente/add/$', generic.CreateView.as_view(model=xt_bioequivalente, form_class=bioeqForm, template_name='modeladorFarmacos/crea_bioequivalente.html'),
        name='bioeq-nuevo',),

    url(r'^modelador_light/admin/modeladorFarmacos/xt_bioequivalente/(?P<pk>\d+)/$', modeladorFarmacos.views.EditaBioequivalente.as_view(),
        name='bioeq-editar',),


##Creacion de productos Segun Kairos
    #    (r'^modelador/catalogo/$', lista_mc),
    (r'^modelador_light/pendientes/$', pendientes),


    (r'^modelador_light/kairos_capsulas/$', kairos2),

    (r'^modelador_light/kairos/$', kairos_global),
    (r'^modelador_light/kairos_tabletas/$', kairos_tabletas),
    (r'^modelador_light/kairos_gotas/$', kairos_gotas),
    (r'^modelador_light/kairos_jarabes/$', kairos_jarabes),
    (r'^modelador_light/kairos_ampollas/$', kairos_ampollas),
    (r'^modelador_light/kairos_colirios/$', kairos_colirios),
    (r'^modelador_light/kairos_cremas/$', kairos_cremas),
    (r'^modelador_light/kairos_parches/$', kairos_parches),
    (r'^modelador_light/kairos_shampoo/$', kairos_shampoo),
    (r'^modelador_light/kairos_supositorios/$', kairos_supositorios),

    ###Efectores CAS
    (r'modelador_light/efectores/imagenes/$', efectoresVistaImagenes),


    (r'^modelador_light/search-form/$', search),

##Repositorio de Documentos
    url(r'^modelador_light/subir/', ArchivosSubidosView.as_view(), name='archivo_upload'),
    url(r'^modelador_light/lista_subidos/(?P<pk>\d+)/$', ArchivoDetalleVista.as_view (),
        name='archivo_subido'),
    url(r'^modelador_light/lista_subidos/', ArchivoIndiceVista.as_view (),
        name='archivo_lista'),
    url(r'^modelador_light/media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'media'}),

##Repositorio de Casos
    url(r'^modelador_light/casos/$', ListCaseView.as_view(),
        name='case-list',),
    url(r'^modelador_light/casos/nuevo', CreateCaseView.as_view(form_class=CasoForm),
        name='case-new',),
    url(r'^modelador_light/casos/editar/(?P<pk>\d+)/$', UpdateCaseView.as_view(),
        name='case-edit',),
    url(r'^modelador_light/casos/borrar/(?P<pk>\d+)/$', DeleteCaseView.as_view(),
        name='case-delete',),
    url(r'^modelador_light/casos/(?P<pk>\d+)/$', CaseView.as_view(),
        name='case-view',),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

modeloNoc/models.py
from django.db import models
from modeloNic.models import nic
from modeloNanda.models import nanda


# Create your models here.
class noc(models.Model):
    titulo = models.CharField(max_length=100)
    descripcion = models.TextField()
    edicion = models.CharField(max_length=40)
    tituloabreviado = models.CharField("Titulo Abreviado",max_length=255, blank=True)
    observacion = models.TextField('Observaciones', blank= True,)
    revisado = models.BooleanField()
    nanda = models.ManyToManyField(nanda, through='relacionNandaNoc')
    nic = models.ManyToManyField(nic, through='relacionNicNoc')
    def __unicode__(self):
        return self.titulo
    class Meta:
        ordering=['id']

class nocDominio(models.Model):
    letra = models.CharField(max_length=10)
    titulo = models.CharField(max_length=100)
    descripcion = models.TextField()
    def __unicode__(self):
        return self.titulo
    class Meta:
        ordering=['id']

class nocClase(models.Model):
    letra = models.CharField(max_length=10)
    titulo = models.CharField(max_length=100)
    descripcion = models.TextField()
    dominio= models.ForeignKey(nocDominio)
    noc = models.ManyToManyField(noc)
    def __unicode__(self):
        return self.titulo
    class Meta:
        ordering=['id']

class nocEscala(models.Model):
    letra = models.CharField(max_length=10)
    titulo = models.CharField(max_length=100)
    codigo1 = models.CharField(max_length=100)
    codigo2 = models.CharField(max_length=100)
    codigo3 = models.CharField(max_length=100)
    codigo4 = models.CharField(max_length=100)
    codigo5 = models.CharField(max_length=100)
    def __unicode__(self):
        return self.titulo
    class Meta:
        ordering=['id']

class nocEspecialidad(models.Model):
    titulo = models.CharField(max_length=100)
    noc = models.ManyToManyField(noc)
    def __unicode__(self):
        return self.titulo
    class Meta:
        ordering=['id']

class nocIndicador(models.Model):
    incadorid = models.IntegerField()
    titulo = models.CharField(max_length=100)
    noc = models.ForeignKey(noc)
    escala = models.ForeignKey(nocEscala)
    def __unicode__(self):
        return self.titulo
    class Meta:
        ordering=['id']

class prioridad(models.Model):
    titulo = models.CharField(max_length=100)
    def __unicode__(self):
        return self.titulo

class relacionNandaNoc(models.Model):
    noc = models.ForeignKey(noc)
    nanda = models.ForeignKey(nanda)
    prioridad = models.ForeignKey(prioridad)


class relacionNicNoc(models.Model):
    noc = models.ForeignKey(noc)
    nic = models.ForeignKey(nic)
    prioridad = models.ForeignKey(prioridad)

repocasos/models.py
from django.core.urlresolvers import reverse
from django.db import models
from django.contrib.auth.models import User
from snomedct.models import sct_description

OPCIONES_INSTITUCION = (
    ('CAS','Clinica Alemana Santiago'),
    ('HPH','Hospital Padre Hurtado'),
    ('CAT','Clinica Alemana Temuco'),
    )

OPCIONES_DOMINIO = (
    ('1','Cuerpo'),
    ('2','Mama'),
    ('3','MSK'),
    ('4','Pediatria'),
    ('5','Neuro'),
    ('4','Otro'),
    )

class BaseModel(models.Model):
    fecha_creacion = models.DateTimeField(null=False, auto_now_add=True)
    usuario_creador = models.ForeignKey(User, null=True, blank=False, editable=False, related_name='%(app_label)s_%(class)s_related_crea')
    fecha_ult_mod = models.DateTimeField(null=True, auto_now=True)
    usuario_ult_mod = models.ForeignKey(User, null=True, blank=False, editable=False, related_name='%(app_label)s_%(class)s_related_modif')

    class Meta:
        abstract = True

class radlex(models.Model):
    name = models.CharField(max_length=255)
    rid = models.CharField(max_length=30, primary_key=True)
    parent = models.CharField(max_length=30)
    def __unicode__(self):

        return unicode(self.name)

class caso(BaseModel):
    fechacaso = models.DateField('Fecha')
    nombre = models.CharField('Nombre',max_length=255)
    appaterno = models.CharField('Apellido Paterno',max_length=255)
    apmaterno = models.CharField('Apellido Materno',max_length=255, blank=True, null=True)
    institucion = models.CharField('Institucion',max_length=5, choices=OPCIONES_INSTITUCION)
    observacion = models.CharField('Observacion',max_length=255)
    dominio = models.CharField(choices=OPCIONES_DOMINIO,max_length=255)
    seguimiento = models.BooleanField(u'Requiere seguimiento?')
    tagging = models.ManyToManyField(sct_description, blank=True)
    url = models.URLField(blank=True)

    def __unicode__(self):

        return unicode(self.observacion)


    def get_absolute_url(self):

        return reverse('case-view', kwargs={'pk': self.id})

    class Meta:
        ordering = ["-fechacaso"]

    def get_field_values(self):
        return [field.value_to_string(self) for field in caso._meta.fields]
#
#class casoForm(ModelForm):
#    class Meta:
#        model = caso
#        fields = ('fechacaso','nombre','appaterno','apmaterno','institucion','observacion')
#        widgets = {
#            'observacion': Textarea(attrs={'cols':80, 'rows':20}),
#        }

templates/caserepo/case.html
{% extends "base.html" %}
{% block branding %}
{% endblock %}

{% block content %}

    <table border=3 cellpadding=3 width=50%>
        <tr>
            <td>
                Fecha de Adquisición
            </td>
            <td>
                {{ caso.fechacaso }}
            </td>
        </tr>
        <tr>
            <td>
                Nombre
            </td>
            <td>
                {{ caso.nombre }}
            </td>
        </tr>
        <tr>
            <td>
                Apellido paterno
            </td>
            <td>
                {{ caso.appaterno }}
            </td>
        </tr>
        <tr>
            <td>
                Apellido Materno
            </td>
            <td>
                {{ caso.apmaterno }}
            </td>
        </tr>
        <tr>
            <td>
                Institución
            </td>
            <td>
                {{ caso.get_institucion_display }}
            </td>
        </tr>
        <tr>
            <td>
                Dominio
            </td>
            <td>
                {{ caso.get_dominio_display }}
            </td>
        </tr>
        <tr>
            <td>
                Observacion
            </td>
            <td>
                {{ caso.observacion }}
            </td>
        </tr>
        <tr>
            <td>
                ¿Requiere seguimiento?
            </td>
            <td>
                {% if caso.seguimiento %}Si{% else %}No{% endif %}
            </td>
        </tr>
        <tr>
            <td>
                MIRC-CAS
            </td>
            <td>
                <a href="{{ caso.url }}" target="_blank">{{ caso.url }}</a>
            </td>
        </tr>

    </table>


{% endblock %}

templates/caserepo/case_list.html
{% extends "base.html" %}

{% block branding %}
{% endblock %}

{% block content %}


<h1>Casos</h1>

{#    <form id="search-form" method="get" action=".">#}
{#        <input type="text" name="FirstName">#}
{#        <input type="submit" value="Buscar" />#}
{#    </form>#}

<table border=3 cellpadding=3 width=100%>
    <tr>
        <td>
            Fecha de Adquisición
        </td>
        <td>
            Observación
        </td>
        <td>
            Etiquetas
        </td>
        <td>
            Dominio
        </td>
        <td>
            ¿Seguimiento?
        </td>
        <td>
            Institución
        </td>
        <td>
            MIRC
        </td>
        <td>
            Edición
        </td>
    </tr>
    {% for caso in object_list %}
{#        <li class="case">#}
{#            <a href="{{ caso.get_absolute_url }}">{{ caso }}</a>#}
{#            (<a href="{% url "case-edit" pk=caso.id %}">editar</a>)#}
{#        </li>#}
        <tr>
            <td>
                {{ caso.fechacaso }}
            </td>
            <td>
                <a href="{{ caso.get_absolute_url }}">{{ caso.observacion }}</a>
            </td>
            <td>
                {% for foo in caso.tagging.all %}
                    {{ foo.term }};
                {% endfor %}

            </td>

            <td>
                {{ caso.get_dominio_display }}
            </td>
            <td>
                {% if caso.seguimiento %}Si{% else %}No{% endif %}
            </td>
            <td>
                {{ caso.institucion }}
            </td>
            <td>
                {% if caso.url  %}  <a href="{{ caso.url }}" target="_blank">Link</a> {% else %}
                {% endif %}
            </td>
            <td>
                <a href="{% url "case-edit" pk=caso.id %}">editar</a>
            </td>
        </tr>
    {% endfor %}
</table>

<a href="{% url "case-new" %}">Agregar nuevo caso</a>
{% endblock %}

templates/caserepo/delete_case.html
{% extends "base.html" %}

{% block branding %}
{% endblock %}
{% block content %}

    <h1>Eliminar Caso</h1>

    <p>¿Está seguro que quiere borrar el caso {{ caso.id }}?</p>

    <form action="{% url "case-delete" pk=caso.id %}" method="POST">
        {% csrf_token %}

        <input type="submit" value="Si, borrar." />
        <a href="{% url "case-list" %}">No, cancela.</a>
    </form>

{% endblock %}

templates/caserepo/edit_case.html
{% extends "base.html" %}
{% load i18n static %}
{% block extrahead %}
    <link rel="stylesheet" type="text/css" href="/modelador_light/static/admin/css/base.css" />
    <link rel="stylesheet" type="text/css" href="/modelador_light/static/admin/css/forms.css" />
    <!--[if lte IE 7]><link rel="stylesheet" type="text/css" href="/modelador_light/static/admin/css/ie.css" /><![endif]-->
    <script type="text/javascript">window.__admin_media_prefix__ = "/modelador_light/static/admin/";</script>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.0/jquery.js" type="text/javascript"></script>
    {% include 'autocomplete_light/static.html' %}
    <script type="text/javascript" src="/modelador_light/my_admin/jsi18n/"></script>
    <script type="text/javascript" src="/modelador_light/static/admin/js/core.js"></script>
    <script type="text/javascript" src="/modelador_light/static/admin/js/admin/RelatedObjectLookups.js"></script>
    <script type="text/javascript" src="/modelador_light/static/admin/js/jquery.js"></script>
    <script type="text/javascript" src="/modelador_light/static/admin/js/jquery.init.js"></script>
    <script type="text/javascript" src="/modelador_light/static/admin/js/actions.js"></script>
    <script type="text/javascript" src="/modelador_light/static/admin/js/calendar.js"></script>
    <script type="text/javascript" src="/modelador_light/static/admin/js/admin/DateTimeShortcuts.js"></script>

    <meta name="robots" content="NONE,NOARCHIVE" />
{% endblock %}

{% block branding %}
{% endblock %}

{% block content %}

{% if caso.id %}
<h1>Editar Caso</h1>
{% else %}
<h1>Agregar nuevo Caso</h1>
{% endif %}

<form action="{{ action }}" method="POST">

    {% csrf_token %}
{#    <ul>#}
{#        {{ form.as_ul }}#}
{#    </ul>#}
    {% if form.non_field_errors %}
        <ul>
            {% for error in form.non_field_errors %}
                <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
{#    {% for field in form %}#}
{#        <div id="{{ field.auto_id }}_container">#}
{#            {{ field.help_text }}#}
{#            <div>#}
{#                {{ field.label_tag }}: {{ field }}#}
{#            </div>#}
{#            <div id="{{ field.auto_id }}_errors">#}
{#                {{ field.errors }}#}
{#            </div>#}
{#        </div>#}
{#    {% endfor %}#}


    <table>
    {% for field in form %}
        <div id="{{ field.auto_id }}_container">
        <tr>
            <td>
                {{ field.label_tag }}:
            </td>
            <td>
                {{ field }}

            <label id="{{ field.auto_id }}_errors">
                {{ field.errors }}
            </label>
            </td>
        </tr>
        </div>
    {% endfor %}
    </table>


    {% if caso.id %}
        <input id="save_case" type="submit" value="Editar" />

        <a href="{% url "case-delete" pk=caso.id %}">Borrar</a>
    {% else %}
        <input id="save_case" type="submit" value="Agregar" />
{#        <input id="save_next_case" type="submit" value="Agregar y Crear Nuevo" />#}
    {% endif %}
</form>

<a href="{% url "case-list" %}">Volver al listado</a>
<br>

{% endblock %}