modeladorsemantiko_light/urls.py
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.conf import settings
# Uncomment the next two lines to enable the admin:

from django.views import generic
import autocomplete_light
from efectorescas.views import efectoresVistaImagenes, search
from modeladorFarmacos.forms import bioeqForm


autocomplete_light.autodiscover()

from django.contrib import admin
admin.autodiscover()

from modeloNanda.api import EntryResource, UserResource
from tastypie.api import Api

from modeladorFarmacos.views import *
import modeladorFarmacos.views

from repodocumentos.views import ArchivoDetalleVista,ArchivosSubidosView,ArchivoIndiceVista
from repocasos.views import ListCaseView,CreateCaseView, UpdateCaseView,DeleteCaseView,CaseView

from repocasos.forms import CasoForm

v1_api = Api(api_name='v1')
v1_api.register(UserResource())
v1_api.register(EntryResource())

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'modeladorsemantiko_light.views.home', name='home'),
    # url(r'^modeladorsemantiko_light/', include('modeladorsemantiko_light.foo.urls')),
    url(r'^modelador_light/autocomplete/', include('autocomplete_light.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^modelador_light/admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^modelador_light/login/$', 'django.contrib.auth.views.login'),
    url(r'^modelador_light/logout/$', 'django.contrib.auth.views.logout'),

    # Uncomment the next line to enable the admin:
    url(r'^modelador_light/admin/', include(admin.site.urls)),

    (r'^modelador_light/api/', include(v1_api.urls)),
    (r'^modelador_light/favicon.ico', generic.RedirectView.as_view(url='http://mozilla.org/favicon.ico')),

    (r'^modelador_light/$', generic.TemplateView.as_view(template_name='index.html')),

    (r'^modelador_light/my_admin/jsi18n', 'django.views.i18n.javascript_catalog'),

    url(r'^modelador_light/xt_pcce/lista_usuarios/$', modeladorFarmacos.views.VistaListaPCCECreadores.as_view(),
        name='creadores_lista',),

    url(r'^modelador_light/xt_pcce/lista_usuarios/(\w+)/$', modeladorFarmacos.views.VistaUsuarioCreadorPCCE.as_view()),

    url(r'^modelador_light/xt_pc/lista_usuarios/$', modeladorFarmacos.views.VistaListaPCCreadores.as_view(),
        name='creadores_lista',),

    url(r'^modelador_light/xt_pc/lista_usuarios/(\w+)/$', modeladorFarmacos.views.VistaUsuarioCreadorPC.as_view()),


    url(r'^modelador_light/xt_pc/lista_pendientes/$', modeladorFarmacos.views.VistaPorRevisarPC.as_view(),
        name='lista_pendientes',),


    url(r'^modelador_light/xt_pcce/lista_pendientes/$', modeladorFarmacos.views.VistaPorRevisarPCCE.as_view(),
        name='lista_pendientes',),


##Vistas Para Creacion de Nuevos Bioequivalentes
    url(r'^modelador_light/bioeq/$', modeladorFarmacos.views.VistaBioequivalente.as_view(),
        name='bioeq-lista',),

    url(r'^modelador_light/admin/modeladorFarmacos/xt_bioequivalente/add/$', generic.CreateView.as_view(model=xt_bioequivalente, form_class=bioeqForm, template_name='modeladorFarmacos/crea_bioequivalente.html'),
        name='bioeq-nuevo',),

    url(r'^modelador_light/admin/modeladorFarmacos/xt_bioequivalente/(?P<pk>\d+)/$', modeladorFarmacos.views.EditaBioequivalente.as_view(),
        name='bioeq-editar',),


##Creacion de productos Segun Kairos
    #    (r'^modelador/catalogo/$', lista_mc),
    (r'^modelador_light/pendientes/$', pendientes),


    (r'^modelador_light/kairos_capsulas/$', kairos2),

    (r'^modelador_light/kairos/$', kairos_global),
    (r'^modelador_light/kairos_tabletas/$', kairos_tabletas),
    (r'^modelador_light/kairos_gotas/$', kairos_gotas),
    (r'^modelador_light/kairos_jarabes/$', kairos_jarabes),
    (r'^modelador_light/kairos_ampollas/$', kairos_ampollas),
    (r'^modelador_light/kairos_colirios/$', kairos_colirios),
    (r'^modelador_light/kairos_cremas/$', kairos_cremas),
    (r'^modelador_light/kairos_parches/$', kairos_parches),
    (r'^modelador_light/kairos_shampoo/$', kairos_shampoo),
    (r'^modelador_light/kairos_supositorios/$', kairos_supositorios),

    ###Efectores CAS
    (r'modelador_light/efectores/imagenes/$', efectoresVistaImagenes),


    (r'^modelador_light/search-form/$', search),

##Repositorio de Documentos
    url(r'^modelador_light/subir/', ArchivosSubidosView.as_view(), name='archivo_upload'),
    url(r'^modelador_light/lista_subidos/(?P<pk>\d+)/$', ArchivoDetalleVista.as_view (),
        name='archivo_subido'),
    url(r'^modelador_light/lista_subidos/', ArchivoIndiceVista.as_view (),
        name='archivo_lista'),
    url(r'^modelador_light/media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': 'media'}),

##Repositorio de Casos
    url(r'^modelador_light/casos/$', ListCaseView.as_view(),
        name='case-list',),
    url(r'^modelador_light/casos/nuevo', CreateCaseView.as_view(form_class=CasoForm),
        name='case-new',),
    url(r'^modelador_light/casos/editar/(?P<pk>\d+)/$', UpdateCaseView.as_view(),
        name='case-edit',),
    url(r'^modelador_light/casos/borrar/(?P<pk>\d+)/$', DeleteCaseView.as_view(),
        name='case-delete',),
    url(r'^modelador_light/casos/(?P<pk>\d+)/$', CaseView.as_view(),
        name='case-view',),

) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

from django.contrib.staticfiles.urls import staticfiles_urlpatterns
urlpatterns += staticfiles_urlpatterns()

modeladorFarmacos/models.py
from django.core.urlresolvers import reverse
from django.db import models
import datetime
from django.utils import timezone
from django.contrib.auth.models import User

OPCIONES_ESTADO = ((0, '0 - Vigente'),(1, '1 - No Vigente'))
OPCIONES_BOOL = ((1,'Si'),(0,'No'))

# Create your models here.

class BaseModel(models.Model):
    fecha_creacion = models.DateTimeField(null=False, auto_now_add=True)
    usuario_creador = models.ForeignKey(User, null=False, blank=False, editable=False, related_name='%(app_label)s_%(class)s_related_crea', default=1)
    fecha_ult_mod = models.DateTimeField(null=True, auto_now=True)
    usuario_ult_mod = models.ForeignKey(User, null=True, blank=False, editable=False, related_name='%(app_label)s_%(class)s_related_modif', default=1)

    class Meta:
        abstract = True

class dbnet (models.Model):
    cod_clasificacion = models.IntegerField()
    clasificacion = models.CharField(max_length=255)
    codigo = models.IntegerField()
    producto = models.CharField(max_length=255)
    receta_retenida = models.IntegerField()
    cod_principio_activo = models.CharField(max_length=255)
    principio_activo = models.CharField(max_length=255)
    cod_concentracion = models.CharField(max_length=255)
    concentracion = models.CharField(max_length=255)
    cod_acc_farmacologica = models.IntegerField()
    accion_farmacologica = models.CharField(max_length=255)
    cod_unidad = models.CharField(max_length=255)
    unidad_medida = models.CharField(max_length=255)
    def __unicode__(self):
        return self.producto


class atc (models.Model):
    cod_atc = models.CharField(max_length=10, primary_key=True)
    n1_cod = models.CharField(max_length=10)
    n1_desc = models.CharField(max_length=255)
    n2_cod = models.CharField(max_length=10)
    n2_desc = models.CharField(max_length=255)
    n3_cod = models.CharField(max_length=10)
    n3_desc = models.CharField(max_length=255)
    n4_cod = models.CharField(max_length=10)
    n4_desc = models.CharField(max_length=255)
    nivelmax = models.IntegerField()
    largo = models.IntegerField()
    atc_desc = models.CharField(max_length=255)

    def __unicode__(self):
        return u"%s > %s > %s > %s > %s > %s" % (
            self.cod_atc
            ,self.atc_desc
            ,self.n1_desc
            ,self.n2_desc
            ,self.n3_desc
            ,self.n4_desc
            )
    class META:
        verbose_name_plural ='Codigos ATC'


class dci (BaseModel):

    dci = models.IntegerField(max_length=10)
    subtanceName = models.CharField(max_length=255)

    def __unicode__(self):
        return self.subtanceName

class registroSanitario(BaseModel):
    registro = models.CharField(max_length=10, primary_key=True)
    ano_caducidad = models.CharField(max_length=2, blank=False,help_text='Usar dos digitos. Ej. 09, 10, 11, etc.')
    nombre = models.CharField(max_length=255)
    titular = models.CharField(max_length=255)

    def __unicode__(self):
        return u"%s/%s - %s" % (self.registro,self.ano_caducidad,self.nombre)

## ##
## table 'kairos_sustancia'
## tabla de sustancias de kairos
## ##



class kairos_sustancia (models.Model):
    clave = models.IntegerField(primary_key=True)
    descripcion = models.CharField(max_length=255)
    tipo = models.CharField(max_length=255)
    fechaalta = models.DateTimeField(null=True)
    fechacambio = models.DateTimeField(null=True)
    estado = models.CharField(max_length=1)

    def __unicode__(self):
        return self.descripcion
    class Meta:
        ordering=['clave']
        verbose_name_plural ='tabla de sustancias de kairos'

## ##-
## table 'kairos_lab'
## laboratorios de kairos
## ##-



class kairos_lab (models.Model):
    clave = models.IntegerField(primary_key=True)
    abreviatura = models.CharField(max_length=255)
    descripcion = models.CharField(max_length=255)
    direccioni = models.CharField(max_length=255)
    localidad = models.CharField(max_length=255)
    ciudad = models.CharField(max_length=255)
    seccion = models.CharField(max_length=255)
    provincia = models.CharField(max_length=255)
    codigopostal = models.CharField(max_length=255)
    telefonos = models.CharField(max_length=255)
    fax = models.CharField(max_length=255)
    tipo = models.CharField(max_length=255)
    web = models.CharField(max_length=255)
    fechaalta = models.DateTimeField(null=True)
    fechacambio = models.DateTimeField(null=True)
    estado = models.CharField(max_length=255)

    def __unicode__(self):
        return u'%s' % (self.abreviatura)
    class Meta:
        ordering=['clave']
        verbose_name_plural ='laboratorios de kairos'


## ##-
## table 'kairos_productos'
## tabla de productos de kairos
## ##-



class kairos_productos (models.Model):
    clave = models.IntegerField(primary_key=True)
    descripcion = models.CharField(max_length=255)
    laboratorioproductor = models.ForeignKey(kairos_lab, null=True,blank=True, related_name='productor')
    laboratoriocomercializador = models.ForeignKey(kairos_lab, null=True,blank=True, related_name='comercializador')
    origen = models.CharField(max_length=255)
    psicofarmaco = models.CharField(max_length=255)
    condicionventa = models.CharField(max_length=255)
    estupefaciente = models.CharField(max_length=255)
    almacenamiento = models.CharField(max_length=255)
    caducidad = models.CharField(max_length=255)
    certificado = models.CharField(max_length=255)
    fechaalta = models.DateTimeField(null=True)
    fechacambio = models.DateTimeField(null=True)
    estado = models.CharField(max_length=255)
    impuesto = models.CharField(max_length=255)
    odontologia = models.CharField(max_length=255)

    def __unicode__(self):
        return u"%s - %s (%s) - %s" % (self.clave,self.descripcion,self.laboratoriocomercializador,self.estado)
    class Meta:
        ordering=['clave']
        verbose_name_plural ='tabla de productos de kairos'

## ##-
## table 'kairos_presentaciones'
## tabla de presentaciones de productos de kairos
## ##-



class kairos_presentaciones (models.Model):
    id_presentacion_kairos = models.IntegerField(primary_key=True)
    claveproducto = models.ForeignKey(kairos_productos)
    clavepresentacion = models.SmallIntegerField()
    concentracion = models.SmallIntegerField()
    unidadconcentracion = models.CharField(max_length=255)
    especificacion = models.CharField(max_length=255)
    viaadministracion = models.CharField(max_length=255)
    medio = models.CharField(max_length=255)
    cantidadenvase = models.SmallIntegerField()
    dosis = models.SmallIntegerField()
    cantidadunidad = models.FloatField(null=True)
    unidadcantidad = models.CharField(max_length=255)
    descripcion = models.CharField(max_length=255)
    factorfraccion = models.SmallIntegerField()
    impuesto = models.CharField(max_length=255)
    porcentajeimpuesto = models.SmallIntegerField()
    listadodescuento = models.CharField(max_length=255)
    uso = models.CharField(max_length=255)
    pami = models.CharField(max_length=255)
    troquel = models.SmallIntegerField()
    ioma = models.CharField(max_length=255)
    tipo = models.CharField(max_length=255)
    sifar = models.CharField(max_length=255)
    codigobarras = models.CharField(max_length=255)
    canasta = models.CharField(max_length=255)
    registro = models.CharField(max_length=255)
    fechaalta = models.DateTimeField(null=True)
    fechacambio = models.DateTimeField(null=True)
    estado = models.CharField(max_length=255)

    def __unicode__(self):
        return u"%s - %s" % (self.claveproducto,self.descripcion)
    class Meta:
        ordering=['id_presentacion_kairos']
        verbose_name_plural ='tabla de presentaciones de productos de kairos'



class kairos_precio(models.Model):
    id_presentacion_kairos = models.AutoField(primary_key=True)
    claveproducto = models.ForeignKey(kairos_productos)
    clavepresentacion = models.ForeignKey(kairos_presentaciones)
    fechaingreso = models.DateField(null=True)
    fechavigencia = models.DateField(null=True)
    preciofabrica = models.FloatField()
    preciopublico = models.FloatField()
    preciofabrica12 = models.FloatField()
    preciopublico12 = models.FloatField()
    preciofabrica17 = models.FloatField()
    preciopublico17 = models.FloatField()
    preciofabrica18 = models.FloatField()
    preciopublico18 = models.FloatField()
    preciofabrica19 = models.FloatField()
    preciopublico19 = models.FloatField()
    def __unicode__(self):
        return u"%s" % self.claveproducto


class kairos_texto_producto(models.Model):
    clave = models.ForeignKey(kairos_productos)
    orden = models.PositiveIntegerField()
    texto = models.TextField()
    def html_texto(self):
        return self.texto
    html_texto.allow_tags = True

    def __unicode__(self):
        return u'%s' % self.clave_id
    class Meta:
        ordering=['id']

#########################################################################


class xt_unidad_dosis_unitaria (models.Model):

    id_xt_unidad_dosis_u = models.AutoField(primary_key=True)

    descripcion = models.CharField(max_length=255)

    fecha_creacion = models.DateTimeField(null=False, auto_now_add=True)
    usuario_creador = models.ForeignKey(User, null=False, blank=False, editable=False, related_name='%(app_label)s_%(class)s_related_crea')
    fecha_ult_mod = models.DateTimeField(null=True, auto_now=True)
    usuario_ult_mod = models.ForeignKey(User, null=True, blank=True, editable=False, related_name='%(app_label)s_%(class)s_related_modif')

    estado = models.PositiveSmallIntegerField(max_length=1,choices=OPCIONES_ESTADO, null=True,default=0)

    sn_descriptionid = models.CharField(max_length=20, null=True, blank=True, verbose_name=u'SNOMED-CT DescriptionID')
    sn_term =   models.CharField(max_length=255, verbose_name=u'SNOMED-CT Termino', null=True, blank=True)

    hiba_descriptionid = models.CharField(max_length=20, null=True, blank=True)

modeladorFarmacos/forms.py
import autocomplete_light

from modeladorFarmacos.models import xt_pcce, xt_pc, xt_bioequivalente

class pcceForm(autocomplete_light.ModelForm):
    class Meta:
        model = xt_pcce

class bioeqForm(autocomplete_light.ModelForm):
    class Meta:
        model = xt_bioequivalente



__author__ = 'ehebel'

templates/modeladorFarmacos/creadores_pcce.html
{% extends "base.html" %}
{% block extrahead %}
    {# These are needed to enable autocompletes in forms #}
    <script src="{{ STATIC_URL }}jquery.js" type="text/javascript"></script>
    {% include 'autocomplete_light/static.html' %}

    Usuarios Creadores PCCE
{% endblock %}

{% block content %}

    <h1>Creadores de PCCE</h1>

    {#{% for pcce in object_list %}#}
    {#    <li>{{ pcce.descripcion }}</li>#}
    {#{% endfor %}#}


    {% regroup object_list by usuario_creador as creadores_pcce %}

    <ul>
        {% for usuario_creador in creadores_pcce %}
            <li><a href="../lista_usuarios/{{ usuario_creador.grouper.id }}">{{ usuario_creador.grouper }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}

templates/modeladorFarmacos/edita_bioequivalente.html
{% extends "base.html" %}
{% block branding %}{% endblock %}
{% block content %}
    <h1>Bioequivalentes</h1>

    <ul>
        {% for producto in object_list %}
            <li class="producto">{{ producto }}
                (<a href="{% url "bioeq_editar" pk=producto.id_xt_bioequivalente %}">editar</a>)
            </li>
        {% endfor %}
    </ul>

    <a href="{% url "bioeq-nuevo" %}">Agregar Bioequivalente</a>
{% endblock %}

templates/modeladorFarmacos/kairos_ampollas.html
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/html">
<head>
    <title>Listado de Kairos</title>
    <style type="text/css">
        .pg-normal {
            color: black;
            font-weight: normal;
            text-decoration: none;
            cursor: pointer;
        }
        .pg-selected {
            color: black;
            font-weight: bold;
            text-decoration: underline;
            cursor: pointer;
        }
    </style>
</head>
<body>
{% extends "base.html" %}

{% block branding %}
    <h1>Catálogo de revisión KAIROS Ampollas, F. Ampollas y Vial</h1>

{% endblock %}



{% block content %}
    <table border=3 cellpadding=3>
        <tr>
            <th>Kairos_Producto</th>
            <th>Kairos_Presentacion</th>
            <th>PCCE</th>
            <th>PC</th>
        </tr>{% for item in kpres_kairos %}
        <tr>
            <td rowspan={% if item.xt_pcce_set.all|length == 0 %}1{% else %}{{ item.xt_pcce_set.all|length }}{% endif %}>
                [{{ item.claveproducto.clave }}] {{ item.claveproducto.descripcion }}
                ({{ item.claveproducto.laboratorioproductor.abreviatura }})

                {#                <a href="../admin/modeladorFarmacos2/kairos_texto_producto/" target="_blank">i</a>#}

            </td>
            <td rowspan={% if item.xt_pcce_set.all|length == 0 %}1{% else %}{{ item.xt_pcce_set.all|length }}{% endif %}>{{ item.descripcion }}
            </td>{% for foo in item.xt_pcce_set.all %}
            <td><a href="/modelador_light/admin/modeladorFarmacos/xt_pcce/{{ foo.id_xt_pcce }}" target="_blank">{{ foo.descripcion }}</a>
            </td>
            <td>
                <a href="/modelador_light/admin/modeladorFarmacos/xt_pc/{{ foo.id_xt_pc.id_xt_pc }}" target="_blank">{{ foo.id_xt_pc.descripcion }}</a>
            </td>
            </tr>
        {% empty %}
            <td>
                <a href="/modelador_light/admin/modeladorFarmacos/xt_pcce/" target="_blank">Sin PCCE!</a>
            </td>
            <td>Sin PC</td>{% endfor %}

    {% endfor %}
    </table>



    <div class="pagination">
        {% if kpres_kairos.has_previous %}
            <a href="?page={{ kpres_kairos.previous_page_number }}">&#171 Anterior</a>
        {% endif %}
        {% for pg in kpres_kairos.paginator.page_range %}
            {% if kpres_kairos.number == pg %}
                <span class="active"><a href="?page={{ pg }}">{{ pg }}</a>|</span>
            {% else %}
                <span><a href="?page={{ pg }}">{{ pg }}</a> |</span>
            {% endif %}
        {% endfor %}
        {% if kpres_kairos.has_next %}
            <span><a href="?page={{ kpres_kairos.next_page_number }}">Siguiente &#187;</a></span>
        {% endif %}
    </div>

{% endblock %}


</body>
</html>

templates/modeladorFarmacos/kairos_base.html
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/html">
<head>
    <title>Listado de Kairos</title>
    <style type="text/css">
        .pg-normal {
            color: black;
            font-weight: normal;
            text-decoration: none;
            cursor: pointer;
        }
        .pg-selected {
            color: black;
            font-weight: bold;
            text-decoration: underline;
            cursor: pointer;
        }
    </style>
</head>
<body>
{% extends "base.html" %}

{% block branding %}
    <h1>Catálogo de revisión KAIROS</h1>

{% endblock %}



{% block content %}
    <table border=3 cellpadding=3 width=100%>
        <tr>
            <th>Kairos_Producto</th>
            <th>Kairos_Presentacion</th>
            <th>PCCE</th>
            <th>PC</th>
        </tr>{% for item in kpres_kairos %}
        <tr>
            <td rowspan={% if item.xt_pcce_set.all|length == 0 %}1{% else %}{{ item.xt_pcce_set.all|length }}{% endif %}>
                [{{ item.claveproducto.clave }}] {{ item.claveproducto.descripcion }}
                ({{ item.claveproducto.laboratorioproductor.abreviatura }})

                {#                <a href="../admin/modeladorFarmacos2/kairos_texto_producto/" target="_blank">i</a>#}

            </td>
            <td rowspan={% if item.xt_pcce_set.all|length == 0 %}1{% else %}{{ item.xt_pcce_set.all|length }}{% endif %}>{{ item.descripcion }}
            </td>{% for foo in item.xt_pcce_set.all %}
            <td><a href="/modelador_light/admin/modeladorFarmacos/xt_pcce/{{ foo.id_xt_pcce }}" target="_blank">{{ foo.descripcion }}</a>
            </td>
            <td>
                <a href="/modelador_light/admin/modeladorFarmacos/xt_pc/{{ foo.id_xt_pc.id_xt_pc }}" target="_blank">{{ foo.id_xt_pc.descripcion }}</a>
            </td>
            </tr>
        {% empty %}
            <td>
                <a href="/modelador_light/admin/modeladorFarmacos/xt_pcce/" target="_blank">Sin PCCE!</a>
            </td>
            <td>Sin PC</td>{% endfor %}

    {% endfor %}
    </table>



    <div class="pagination">
        {% if kpres_kairos.has_previous %}
            <a href="?page={{ kpres_kairos.previous_page_number }}">&#171 Anterior</a>
        {% endif %}
        {% for pg in kpres_kairos.paginator.page_range %}
            {% if kpres_kairos.number == pg %}
                <span class="active"><a href="?page={{ pg }}">{{ pg }}</a>|</span>
            {% else %}
                <span><a href="?page={{ pg }}">{{ pg }}</a> |</span>
            {% endif %}
        {% endfor %}
        {% if kpres_kairos.has_next %}
            <span><a href="?page={{ kpres_kairos.next_page_number }}">Siguiente &#187;</a></span>
        {% endif %}
    </div>

{% endblock %}


</body>
</html>

templates/modeladorFarmacos/lista_bioequivalentes.html
{% extends "base.html" %}
{% block branding %}{% endblock %}

{% block content %}
    <h1>Bioequivalentes</h1>
    <a href="{% url "bioeq-nuevo" %}">Agregar Bioequivalentes</a>

    <ul>
        {% for producto in object_list %}
            <li class="producto">{{ producto }}
                (<a href="{% url "bioeq-editar" pk=producto.id_xt_bioequivalente %}">editar</a>)
            </li>
        {% endfor %}
    </ul>

{% endblock %}

templates/modeladorFarmacos/listado_trabajo.html
<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/html">
<head>
    <title>Listado de Trabajo</title>
</head>
<body>
{% extends "base.html" %}
{% block content %}

    Se han encontrado {{ pendientes_mc|length }} MC con Bioequivalentes

    <table border=3 cellpadding=5>

        <tr>
            <th>xt_mc</th>
            <th>xt_pc</th>
            <th>xt_pcce</th>
            <th>referente</th>
        </tr>
        {% for item in pendientes_mc %}
            <tr>
                <td rowspan={{ item.xt_pc_set.all|length }}>
                    <a href="/modelador_light/admin/modeladorFarmacos/xt_mc/{{ item.id_xt_mc }}">{{ item.descripcion }}</a>
                    {% for pc in item.xt_pc_set.all %}
                        </td>
                        <td>
                            <a href="/modelador_light/admin/modeladorFarmacos2/xt_pc/{{ pc.id_xt_pc }}">{{ pc.descripcion }}</a>
                        </td>
                        <td>
                            {% for pcce in pc.xt_pcce_set.all %}
                                <li><a href="/modelador_light/admin/modeladorFarmacos/xt_pcce/{{ pcce.id_xt_pcce }}">{{ pcce.descripcion }} [{{ pcce.id_xt_mcce.get_tipo_display }}]</a>

                                    {#                                {% for bar in pcce.id_presentacion_kairos.id_kairos_precio.all %}#}
                                    {#                                 ($ {{ bar.id_presentacion_kairos }} )#}
                                    {#                                {% endfor %}#}

                                </li>
                            {% empty %}
                                <a href="/modelador_light/admin/modeladorFarmacos/xt_pcce/">Sin PCCE!</a>
                            {% endfor %}

                        </td>
                        <td>
                            {% for foo in pc.equivalente.all %}
                                <li><a href="/modelador_light/admin/modeladorFarmacos/xt_pc/{{ foo.id_xt_pc }}"> {{ foo.descripcion }} </a></li>
                            {% empty %}
                                {% if pc.id_xt_pc in bioeq_referentes %}
                                    <span style="color: red">Referente</span>

                                {% elif pc.id_xt_pc not in bioeq_referentes %}

                                    <span style="color: #ff8c00">No Certificado</span>

                                {% endif %}
                            {% endfor %}
                        </td>
                        </tr>
                        <tr>
                    {% endfor %}
        {% endfor %}
        </tr>
    </table>

    <div class="pagination">
        {% if pendientes_mc.has_previous %}
            <a href="?page={{ pendientes_mc.previous_page_number }}">&#171 Anterior</a>
        {% endif %}
        {% for pg in pendientes_mc.paginator.page_range %}
            {% if pendientes_mc.number == pg %}
                <span class="active"><a href="?page={{ pg }}">{{ pg }}</a>|</span>
            {% else %}
                <span><a href="?page={{ pg }}">{{ pg }}</a> |</span>
            {% endif %}
        {% endfor %}
        {% if pendientes_mc.has_next %}
            <span><a href="?page={{ pendientes_mc.next_page_number }}">Siguiente &#187;</a></span>
        {% endif %}
    </div>

    {% if var in bioeq_referentes %}

    {% endif %}

    <div>
        {% for baz in bioeq_referentes %}
            {{ baz.referencia }}
        {% endfor %}
    </div>

{% endblock %}
</body>
</html>

templates/modeladorFarmacos/pcce_detalle.html
<!DOCTYPE html>
<html>
<head>
    <title></title>
</head>
<body>
{% extends "base.html" %}

{% block content %}

    <p>Descripcion: {{ xt_pcce.descripcion }}</p>

{% endblock %}

</body>
</html>